import Foundation

class LocalizationManager {
    static let shared = LocalizationManager()

    private let translations: [String: [String: String]] = [
        "en": [
            "home": "Home",
            "tables": "Tables",
            "custom": "Custom",
            "settings": "Settings",
            "apnea_trainer": "Apnea Trainer",
            "breathe_hold_conquer": "Breathe. Hold. Conquer.",
            "quick_start": "Quick Start",
            "training_tables": "Training Tables",
            "preset_tables": "Preset Tables",
            "levels": "levels",
            "hold_time": "Hold Time",
            "rest_time": "Rest Time",
            "build_your_table": "Build Your Table",
            "save": "Save",
            "start": "Start",
            "cancel": "Cancel",
            "saved_tables": "Saved Tables",
            "no_saved_tables": "No saved tables yet",
            "table_name": "Table name",
            "enter_table_name": "Enter a name for your custom table",
            "app_language": "App Language",
            "changes_language": "Changes the app interface language",
            "countdown_voice": "Countdown Voice",
            "voice_used_for_time_announcements": "Voice used for time announcements during training",
            "female_voice": "Female Voice",
            "male_voice": "Male Voice",
            "announcement_interval": "Announcement Interval",
            "how_often_voice_announces": "How often the voice announces remaining time",
            "every": "Every",
            "about": "About",
            "freediving_breath_hold_training": "A freediving breath-hold training app",
            "version": "Version",
            "ready": "Ready",
            "get_ready": "Get Ready",
            "hold_your_breath": "Hold Your Breath",
            "rest": "Rest",
            "rest_label": "Rest",
            "completed": "Completed!",
            "stop": "Stop",
            "restart": "Restart",
            "level": "Level",
            "hold": "Hold",
            "seconds": "seconds",
        ],
        "pl": [
            "home": "Dom",
            "tables": "Tabele",
            "custom": "Własna",
            "settings": "Ustawienia",
            "apnea_trainer": "Apnea Trainer",
            "breathe_hold_conquer": "Oddychaj. Wstrzymaj. Zdominuj.",
            "quick_start": "Szybki start",
            "training_tables": "Tabele treningowe",
            "preset_tables": "Gotowe tabele",
            "levels": "poziomy",
            "hold_time": "Czas wstrzymania",
            "rest_time": "Czas odpoczynku",
            "build_your_table": "Stwórz swoją tabelę",
            "save": "Zapisz",
            "start": "Start",
            "cancel": "Anuluj",
            "saved_tables": "Zapisane tabele",
            "no_saved_tables": "Brak zapisanych tabel",
            "table_name": "Nazwa tabeli",
            "enter_table_name": "Wprowadź nazwę dla swojej tabeli",
            "app_language": "Język aplikacji",
            "changes_language": "Zmienia język interfejsu aplikacji",
            "countdown_voice": "Głos odliczania",
            "voice_used_for_time_announcements": "Głos używany do ogłaszania czasu podczas treningu",
            "female_voice": "Głos żeński",
            "male_voice": "Głos męski",
            "announcement_interval": "Interwał ogłaszania",
            "how_often_voice_announces": "Jak często głos ogłasza pozostały czas",
            "every": "Co",
            "about": "O aplikacji",
            "freediving_breath_hold_training": "Aplikacja do treningu wstrzymywania oddechu w freedivingu",
            "version": "Wersja",
            "ready": "Gotowy",
            "get_ready": "Przygotuj się",
            "hold_your_breath": "Wstrzymaj oddech",
            "rest": "Odpoczynek",
            "rest_label": "Odpoczynek",
            "completed": "Ukończono!",
            "stop": "Stop",
            "restart": "Restart",
            "level": "Poziom",
            "hold": "Wstrzymanie",
            "seconds": "sekund",
        ],
        "sv": [
            "home": "Hem",
            "tables": "Tabeller",
            "custom": "Anpassad",
            "settings": "Inställningar",
            "apnea_trainer": "Apnea Trainer",
            "breathe_hold_conquer": "Andas. Håll. Behärska.",
            "quick_start": "Snabbstart",
            "training_tables": "Träningstabeller",
            "preset_tables": "Förinställda tabeller",
            "levels": "nivåer",
            "hold_time": "Hålltid",
            "rest_time": "Vilotid",
            "build_your_table": "Skapa din tabell",
            "save": "Spara",
            "start": "Starta",
            "cancel": "Avbryt",
            "saved_tables": "Sparade tabeller",
            "no_saved_tables": "Inga sparade tabeller ännu",
            "table_name": "Tabellnamn",
            "enter_table_name": "Ange ett namn för din anpassade tabell",
            "app_language": "Appspråk",
            "changes_language": "Ändrar appens gränssnittsspråk",
            "countdown_voice": "Nedröstningsröst",
            "voice_used_for_time_announcements": "Röst som används för tidsmeddelanden under träning",
            "female_voice": "Kvinnoröst",
            "male_voice": "Manlig röst",
            "announcement_interval": "Meddelandeintervall",
            "how_often_voice_announces": "Hur ofta rösten meddelar återstående tid",
            "every": "Var",
            "about": "Om",
            "freediving_breath_hold_training": "En app för fridykning med andhållningsträning",
            "version": "Version",
            "ready": "Redo",
            "get_ready": "Gör dig redo",
            "hold_your_breath": "Håll andan",
            "rest": "Vila",
            "rest_label": "Vila",
            "completed": "Klart!",
            "stop": "Stopp",
            "restart": "Starta om",
            "level": "Nivå",
            "hold": "Håll",
            "seconds": "sekunder",
        ],
        "ru": [
            "home": "Главная",
            "tables": "Таблицы",
            "custom": "Своя",
            "settings": "Настройки",
            "apnea_trainer": "Apnea Trainer",
            "breathe_hold_conquer": "Дыши. Держи. Покоряй.",
            "quick_start": "Быстрый старт",
            "training_tables": "Таблицы тренировок",
            "preset_tables": "Готовые таблицы",
            "levels": "уровней",
            "hold_time": "Время задержки",
            "rest_time": "Время отдыха",
            "build_your_table": "Создайте свою таблицу",
            "save": "Сохранить",
            "start": "Старт",
            "cancel": "Отмена",
            "saved_tables": "Сохранённые таблицы",
            "no_saved_tables": "Нет сохранённых таблиц",
            "table_name": "Название таблицы",
            "enter_table_name": "Введите название для вашей таблицы",
            "app_language": "Язык приложения",
            "changes_language": "Изменяет язык интерфейса приложения",
            "countdown_voice": "Голос обратного отсчёта",
            "voice_used_for_time_announcements": "Голос для объявления времени во время тренировки",
            "female_voice": "Женский голос",
            "male_voice": "Мужской голос",
            "announcement_interval": "Интервал объявлений",
            "how_often_voice_announces": "Как часто голос объявляет оставшееся время",
            "every": "Каждые",
            "about": "О приложении",
            "freediving_breath_hold_training": "Приложение для тренировки задержки дыхания в фридайвинге",
            "version": "Версия",
            "ready": "Готов",
            "get_ready": "Приготовьтесь",
            "hold_your_breath": "Задержите дыхание",
            "rest": "Отдых",
            "rest_label": "Отдых",
            "completed": "Завершено!",
            "stop": "Стоп",
            "restart": "Перезапуск",
            "level": "Уровень",
            "hold": "Задержка",
            "seconds": "секунд",
        ],
    ]

    func localized(_ key: String) -> String {
        let lang = UserDefaults.standard.string(forKey: "appLanguage") ?? "en"
        return translations[lang]?[key] ?? translations["en"]?[key] ?? key
    }
}

func L(_ key: String) -> String {
    LocalizationManager.shared.localized(key)
}
